Output doc/tapes/aliases.gif

Set Shell "zsh"
Set FontSize 20
Set Width 1200
Set Height 400
Set WindowBar Colorful
Set Theme "Catppuccin Frappe"
Set BorderRadius 10

Type "mojo build examples/aliases.mojo -o aliases" Sleep 500ms  Enter
Sleep 2s
Type "./aliases" Sleep 500ms  Enter
Sleep 2s
Type "./aliases tool" Sleep 500ms  Enter
Sleep 2s
Type "./aliases object" Sleep 500ms  Enter
Sleep 2s
Type "./aliases thing" Sleep 500ms  Enter
Sleep 1s
Sleep 5s
