import std.testing
from std.memory import OwnedPointer
from prism import Command, Completion, FlagSet
from prism.flag import Flag
from prism.completion import generate_zsh_completion, _zsh_escape, _zsh_flag_spec
from std.testing import TestSuite


fn dummy(args: List[String], flags: FlagSet) raises -> None:
    pass


def test_zsh_escape_plain_text() raises:
    std.testing.assert_equal(_zsh_escape("simple text"), "simple text")


def test_zsh_escape_single_quotes() raises:
    std.testing.assert_equal(_zsh_escape("it's"), "it'\\''s")


def test_zsh_escape_colons() raises:
    std.testing.assert_equal(_zsh_escape("key:value"), "key\\:value")


def test_zsh_escape_brackets() raises:
    std.testing.assert_equal(_zsh_escape("[option]"), "\\[option\\]")


def test_zsh_flag_spec_bool_with_shorthand() raises:
    var flag = Flag.bool(name="verbose", shorthand="v", usage="Enable verbose output")
    var spec = _zsh_flag_spec(flag)
    std.testing.assert_equal(spec, "'(-v --verbose)'{-v,--verbose}'[Enable verbose output]'")


def test_zsh_flag_spec_bool_no_shorthand() raises:
    var flag = Flag.bool(name="debug", usage="Enable debug mode")
    var spec = _zsh_flag_spec(flag)
    std.testing.assert_equal(spec, "'--debug[Enable debug mode]'")


def test_zsh_flag_spec_string_with_shorthand() raises:
    var flag = Flag.string(name="env", shorthand="e", usage="Environment")
    var spec = _zsh_flag_spec(flag)
    std.testing.assert_equal(spec, "'(-e --env)'{-e,--env}'=[Environment]:env:'")


def test_zsh_flag_spec_string_no_shorthand() raises:
    var flag = Flag.string(name="host", usage="Host name")
    var spec = _zsh_flag_spec(flag)
    std.testing.assert_equal(spec, "'--host=[Host name]:host:'")


def test_zsh_flag_spec_int() raises:
    var flag = Flag.int(name="port", shorthand="p", usage="Port number")
    var spec = _zsh_flag_spec(flag)
    std.testing.assert_equal(spec, "'(-p --port)'{-p,--port}'=[Port number]:port:'")


def test_zsh_flag_spec_string_list() raises:
    var flag = Flag.string_list(name="hosts", usage="Host list")
    var spec = _zsh_flag_spec(flag)
    std.testing.assert_equal(spec, "'*--hosts=[Host list]:hosts:'")


def test_zsh_basic_root_command() raises:
    var cmd = OwnedPointer(Command(
        name="myapp",
        usage="My application",
        run=dummy,
    ))
    var script = generate_zsh_completion(cmd)
    # Verify header
    std.testing.assert_true("#compdef myapp" in script)
    std.testing.assert_true("Generated by prism" in script)
    # Verify root function exists
    std.testing.assert_true("_myapp()" in script)
    # Verify entry point handles both source and fpath loading
    std.testing.assert_true('_myapp "$@"' in script)
    std.testing.assert_true('compdef _myapp myapp' in script)
    # Verify help flag is present
    std.testing.assert_true("--help" in script)


def test_zsh_command_with_children() raises:
    var cmd = OwnedPointer(Command(
        name="myapp",
        usage="My application",
        run=dummy,
        children=[
            Command(name="serve", usage="Start server", run=dummy),
            Command(name="build", usage="Build project", run=dummy),
        ],
    ))
    var script = generate_zsh_completion(cmd)
    # Verify child functions exist
    std.testing.assert_true("_myapp__serve()" in script)
    std.testing.assert_true("_myapp__build()" in script)
    # Verify subcommand list in root function
    std.testing.assert_true("'serve:Start server'" in script)
    std.testing.assert_true("'build:Build project'" in script)
    # Verify state machine dispatching
    std.testing.assert_true("serve) _myapp__serve" in script)
    std.testing.assert_true("build) _myapp__build" in script)


def test_zsh_nested_commands() raises:
    var cmd = OwnedPointer(Command(
        name="myapp",
        usage="My application",
        run=dummy,
        children=[
            Command(
                name="sub",
                usage="Sub command",
                run=dummy,
                children=[
                    Command(name="nested", usage="Nested command", run=dummy),
                ],
            ),
        ],
    ))
    var script = generate_zsh_completion(cmd)
    # Verify deeply nested function name uses double-underscore separator
    std.testing.assert_true("_myapp__sub__nested()" in script)
    # Verify parent dispatches to child
    std.testing.assert_true("nested) _myapp__sub__nested" in script)


def test_zsh_command_with_aliases() raises:
    var cmd = OwnedPointer(Command(
        name="myapp",
        usage="My application",
        run=dummy,
        children=[
            Command(
                name="connect",
                usage="Connect to database",
                run=dummy,
                aliases=["conn", "db-connect"],
            ),
        ],
    ))
    var script = generate_zsh_completion(cmd)
    # Verify aliases appear in case pattern
    std.testing.assert_true("connect|conn|db-connect) _myapp__connect" in script)


def test_zsh_command_with_valid_args() raises:
    var cmd = OwnedPointer(Command(
        name="myapp",
        usage="My application",
        run=dummy,
        valid_args=["start", "stop", "restart"],
    ))
    var script = generate_zsh_completion(cmd)
    # Verify valid args appear as completions
    std.testing.assert_true("(start stop restart)" in script)


def test_zsh_command_with_flags() raises:
    var cmd = OwnedPointer(Command(
        name="myapp",
        usage="My application",
        run=dummy,
        flags=[
            Flag.string(name="config", shorthand="c", usage="Config file"),
            Flag.bool(name="verbose", shorthand="v", usage="Verbose output"),
            Flag.int(name="port", usage="Port number"),
        ],
    ))
    var script = generate_zsh_completion(cmd)
    std.testing.assert_true("--config" in script)
    std.testing.assert_true("--verbose" in script)
    std.testing.assert_true("--port" in script)


def test_zsh_completion_subcommand_auto_added() raises:
    var cmd = Command(
        name="myapp",
        usage="My application",
        run=dummy,
        completion=Completion(),
    )
    # Verify completion subcommand was auto-added
    var found = False
    for child in cmd.children:
        if child[].name == "completion":
            found = True
            break
    std.testing.assert_true(found)


def test_zsh_completion_subcommand_in_script() raises:
    var cmd = OwnedPointer(Command(
        name="myapp",
        usage="My application",
        run=dummy,
        completion=Completion(),
    ))
    var script = generate_zsh_completion(cmd)
    # The completion subcommand should appear in the generated script
    std.testing.assert_true("'completion:Generate shell completion scripts.'" in script)
    std.testing.assert_true("_myapp__completion()" in script)


def test_unsupported_shell() raises:
    from prism.completion import default_completion

    var cmd = OwnedPointer(Command(
        name="myapp",
        usage="My application",
        run=dummy,
    ))
    var raised = False
    try:
        _ = default_completion(cmd, "bash")
    except:
        raised = True
    std.testing.assert_true(raised)


fn main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
