[project]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["https://repo.prefix.dev/mojo-community", "conda-forge", "https://conda.modular.com/max"]
description = "A Budding CLI Library!"
name = "prism"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "25.2.1"
license = "MIT"
license-file = "LICENSE"
homepage = "https://github.com/thatstoasty/prism"
repository = "https://github.com/thatstoasty/prism"

[tasks]
tests = "python scripts/util.py run tests"
benchmarks = "python scripts/util.py run benchmarks"
examples = "bash scripts/examples.sh"
template = "python scripts/util.py templater"
build = { cmd = "python scripts/util.py build", env = {MODULAR_MOJO_IMPORT_PATH = "$CONDA_PREFIX/lib/mojo"} }
publish = { cmd = "python scripts/util.py publish", env = { PREFIX_API_KEY = "$PREFIX_API_KEY" } }
bp = { depends-on=["build", "publish"] }

[dependencies]
max = ">=25.2.0,<25.3.0"
mog = ">=25.2.0,<25.3.0"
