[project]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["https://repo.prefix.dev/mojo-community", "conda-forge", "https://conda.modular.com/max"]
description = "A Budding CLI Library!"
name = "prism"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.2"

[tasks]
tests = "bash scripts/tests.sh"
examples = "bash scripts/examples.sh"
build = "rattler-build build -r src -c https://repo.prefix.dev/mojo-community -c https://conda.modular.com/max -c conda-forge --skip-existing=all"
publish = { cmd = "bash scripts/publish.sh", env = { PREFIX_API_KEY = "$PREFIX_API_KEY" } }

[dependencies]
max = ">=24.5.0,<25"
gojo = ">=0.1.9,<0.2"
