[workspace]
description = "A budding CLI Library!"
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["https://repo.prefix.dev/mojo-community", "conda-forge", "https://conda.modular.com/max", "https://prefix.dev/pixi-build-backends"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/thatstoasty/prism"
repository = "https://github.com/thatstoasty/prism"
preview = ["pixi-build"]

[feature.util.tasks]
tests = "mojo test"
benchmarks = "python3 scripts/util.py run-benchmarks"
examples = "bash scripts/examples.sh"
template = "python3 scripts/util.py generate-recipe"

# Linting and Formatting
lint_docs = "python3 scripts/check-docstrings.py"
mojo_format = "mojo format prism --line-length 120"
sort_imports = "isort **/*.mojo -m 3 --line-length 120 --lines-after-imports 2 --trailing-comma"
format = [{ task = "mojo_format" }, { task = "sort_imports" }]

# Build and publish
build = { cmd = "pixi build -o ." }
publish = { cmd = "find . -name 'prism-*.conda' | xargs pixi upload https://prefix.dev/api/v1/upload/mojo-community" }
build_and_publish = [{ task = "build" }, { task = "publish" }]

[package]
name = "prism"
version = "25.5.0"

[package.build]
backend = { name = "pixi-build-mojo", version = "*" }

[dependencies]
mojo = ">=25.5.0,<25.6.0"
mog = ">=25.5.0,<25.6.0"

[package.build-dependencies]
mojo-compiler = ">=25.5.0,<25.6.0"
mog = ">=25.5.0,<25.6.0"

[package.host-dependencies]
mojo = ">=25.5.0,<25.6.0"

[package.run-dependencies]
mojo = ">=25.5.0,<25.6.0"
mog = ">=25.5.0,<25.6.0"

[feature.util.dependencies]
typer = ">=0.16.0,<0.17"
isort = ">=6.0.1,<7"

[environments]
default = { solve-group = "default" }
util = { features = ["util"], solve-group = "default" }
