[workspace]
description = "A budding CLI Library!"
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/thatstoasty/prism"
repository = "https://github.com/thatstoasty/prism"
preview = ["pixi-build"]

[tasks]
tests = "sh -c 'status=0; for f in test/test_*.mojo; do echo \"== $f\"; mojo -D ASSERT=all -I . \"$f\" || status=1; done; exit $status'"
examples = "python3 utils/examples.py"
test_readme_examples = "python3 utils/test_readme_examples.py"

# Linting and Formatting
lint_docs = "mojo doc --Werror --diagnose-missing-doc-strings -o /dev/null ./prism"
mojo_format = "mojo format prism --line-length 120"
format = [{ task = "mojo_format" }]

[package]
name = "prism"
version = "0.4.0"

[package.build]
backend = { name = "pixi-build-mojo", version = "*" }

[dependencies]
mojo = ">=1.0.0,<1.1.0"
mog = { git = "https://github.com/thatstoasty/mog.git", tag = "v0.3.0" }

[package.build-dependencies]
mojo-compiler = ">=1.0.0,<1.1.0"
mog = { git = "https://github.com/thatstoasty/mog.git", tag = "v0.3.0" }

[package.host-dependencies]
mojo = ">=1.0.0,<1.1.0"

[package.run-dependencies]
mojo = ">=1.0.0,<1.1.0"
mog = { git = "https://github.com/thatstoasty/mog.git", tag = "v0.3.0" }
