[project]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["https://repo.prefix.dev/mojo-community", "conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "requests"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.3.0,<25.4.0"
prism = ">=25.3.0,<25.4.0"
requests = ">=2.32.3,<3"
