[workspace]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://prefix.dev/pixi-build-backends"]
description = "Add a short description here"
name = "requests"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
mojo = ">=0.26.2.0,<0.26.3.0"
prism = { path = "../.." }
requests = ">=2.32.3,<3"
