[workspace]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "requests"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
mojo = ">=1.0.0,<1.1.0"
prism = { path = "../.." }
requests = ">=2.32.3,<3"
