[project]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["https://repo.prefix.dev/mojo-community", "conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "printer"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
mist = ">=0.1.8,<0.2"
prism = ">=0.1.5,<0.2"
