[workspace]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["https://repo.prefix.dev/mojo-community", "conda-forge", "https://conda.modular.com/max", "https://prefix.dev/pixi-build-backends"]
description = "Add a short description here"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
preview = ["pixi-build"]

[package]
name = "printer"
version = "0.1.0"

[tasks]

[package.build]
backend = { name = "pixi-build-mojo", version = "*" }

[dependencies]
mojo = ">=0.25.7.0,<0.26.1.0"
mist = ">=25.7.0,<26.1.0"
prism = { path = "../.." }
