Output demos/tapes/aliases.gif

Set Shell "zsh"
Set FontSize 20
Set Width 1200
Set Height 400

Type "mojo run examples/aliases/root.mojo" Sleep 500ms  Enter
Sleep 2s
Type "mojo run examples/aliases/root.mojo tool" Sleep 500ms  Enter
Sleep 2s
Type "mojo run examples/aliases/root.mojo object" Sleep 500ms  Enter
Sleep 2s
Type "mojo run examples/aliases/root.mojo thing" Sleep 500ms  Enter
Sleep 1s
Sleep 5s
