name: build

on:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  build:
    strategy:
      matrix:
        include:
          - { target: linux-64, os: ubuntu-latest }
          - { target: osx-arm64, os: macos-latest }
          - { target: linux-aarch64, os: ubuntu-24.04-arm }
      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.47.0

      - name: Build package for target platform
        env:
          TARGET_PLATFORM: ${{ matrix.target }}
          PREFIX_API_KEY: ${{ secrets.PREFIX_API_KEY }}

        run: |
          # Build and publish
          pixi auth login prefix.dev --token "$PREFIX_API_KEY"
          pixi run build_and_publish
