name: Build all packages

on:
  push:
    branches:
      - nightly
    paths:
        - src/**

# on: ["push"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - { target: linux-64, os: ubuntu-latest }
          - { target: osx-arm64, os: macos-14 }
      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build package for target platform
        env:
          TARGET_PLATFORM: ${{ matrix.target }}
          PREFIX_API_KEY: ${{ secrets.PREFIX_API_KEY }}
          CONDA_BLD_PATH: ${{ runner.workspace }}/.rattler

        run: |
          curl -ssL https://magic.modular.com | bash
          source $HOME/.bash_profile

          # Temporary method to fetch the rattler binary.
          RATTLER_BINARY="rattler-build-aarch64-apple-darwin"
          if [[ $TARGET_PLATFORM == "linux-64" ]]; then RATTLER_BINARY="rattler-build-x86_64-unknown-linux-musl"; fi
          curl -SL --progress-bar https://github.com/prefix-dev/rattler-build/releases/latest/download/${RATTLER_BINARY} -o rattler-build
          chmod +x rattler-build

          # Build and push
          magic run -e nightly build -m nightly
          magic run -e nightly publish -c mojo-community-nightly
