name: Create package

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: read

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - uses: prefix-dev/setup-pixi@v0.8.10
          with:
            pixi-version: v0.47.0

        - name: Run the package command
          run: pixi run mojo package src/mojo_tlse -o mojo_tlse.mojopkg
