name: Run Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    strategy:
      matrix:
        include:
          - { target: linux-64, os: ubuntu-latest }
          - { target: osx-arm64, os: macos-latest }
          - { target: linux-aarch64, os: ubuntu-24.04-arm }
      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install magic
        run: |
          if [[ ${{ matrix.target }} == "linux-aarch64" ]]; then
            bash scripts/install_magic_aarch64.sh
          else
            curl -ssL https://magic.modular.com | bash
          fi

      - name: Run tests
        run: |
          source $HOME/.bash_profile
          magic run tests
