name: tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    name: with ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: ["ubuntu-latest"]
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install magic
        run: |
          curl -ssL https://magic.modular.com | bash

      - name: Run tests
        run: |
          source $HOME/.bash_profile
          magic run tests
          magic run examples
